apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: payment-simulation-platform
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080