dependencies {
    // 모든 모듈 의존성 추가
    implementation project(':auth-module')
    implementation project(':payment-module')
    implementation project(':point-module')
    implementation project(':coupon-module')
    
    // Spring Data JPA는 app 모듈에서도 필요 (EnableJpaRepositories 사용)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
}
